//Blog

export const GET_BLOG_DETAILS = "GET_BLOG_DETAILS";
export const GET_BLOG_DETAILS_SUCCESS = "GET_BLOG_DETAILS_SUCCESS";

//Contact Us

export const GET_CONTACT_DETAIL="GET_CONTACT_DETAIL";


//PORTFOLIO

export const GET_PORTFOLIO_DETAILS = "GET_PORTFOLIO_DETAILS";
export const GET_PORTFOLIO_DETAILS_SUCCESS = "GET_PORTFOLIO_DETAILS_SUCCESS";

//ANOUT US  

export const GET_PILLERS="PILLERS_ARE_GET";
export const GET_PILLERS_SUSCESS="GET_PILLERS_SUSCESS";

export const GET_CUSTOMER="CUSTOMER_ARE_GET";
export const GET_CUSTOMER_SUSCESS="GET_CUSTOMER_SUSCESS";

export const GET_HEALTHCARE="HEALTHCARE_ARE_GET";
export const GET_HEALTHCARE_SUSCESS="GET_HEALTHCARE_SUSCESS";


//HOME

//Our Client
export const SENT_CLIENT_DATA="SENT_CLIENTS_DATA";
export const GET_CLIENT_DATA="GET_CLIENTS_DATA";

//Resources
export const SENT_RESOURCES_DATA="SENT_RESOURCES_DATA";
export const GET_RESOURCES_DATA="GET_RESOURCES_DATA";

export const SENT_APP_DATA = 'SENT_APP_DATA'
export const GET_APP_DATA = 'GET_APP_DATA'


export const SENT_CHOOSE_DATA = 'SENT_CHOOSE_DATA'
export const GET_CHOOSE_DATA = 'GET_CHOOSE_DATA'

export const SENT_BENEFITS_DATA = 'SENT_BENEFITS_DATA'
export const GET_BENEFITS_DATA = 'GET_BENEFITS_DATA'

export const SENT_FEATURE_LIST = 'SENT_FEATURE_LIST'
export const GET_FEATURE_LIST = 'GET_FEATURE_LIST'

//****HOME****//


